import "@/app/ui/global.css";
import { inter } from "@/app/ui/fonts";

export const metadata = {
  title: "VISION",
  description: "Generated by a very tired individual.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} antialised`}>{children}</body>
    </html>
  );
}
